/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApuntarseRouteImport } from './routes/apuntarse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBarraRouteImport } from './routes/_authenticated/barra'
import { Route as AuthenticatedCamareroRouteImport } from './routes/_authenticated/camarero'
import { Route as AuthenticatedCocinaRouteImport } from './routes/_authenticated/cocina'
import { Route as AuthenticatedComandasRouteImport } from './routes/_authenticated/comandas'
import { Route as AuthenticatedDePieRouteImport } from './routes/_authenticated/de-pie'
import { Route as AuthenticatedEsperaRouteImport } from './routes/_authenticated/espera'
import { Route as AuthenticatedExistenciasRouteImport } from './routes/_authenticated/existencias'
import { Route as AuthenticatedFiadoRouteImport } from './routes/_authenticated/fiado'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as MTokenRouteImport } from './routes/m.$token'
import { Route as AuthenticatedAdminAjustesRouteImport } from './routes/_authenticated/admin.ajustes'
import { Route as AuthenticatedAdminArticulosRouteImport } from './routes/_authenticated/admin.articulos'
import { Route as AuthenticatedAdminCartaImpresaRouteImport } from './routes/_authenticated/admin.carta-impresa'
import { Route as AuthenticatedAdminMesasRouteImport } from './routes/_authenticated/admin.mesas'
import { Route as AuthenticatedAdminPersonalRouteImport } from './routes/_authenticated/admin.personal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApuntarseRoute = ApuntarseRouteImport.update({
  id: '/apuntarse',
  path: '/apuntarse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBarraRoute = AuthenticatedBarraRouteImport.update({
  id: '/barra',
  path: '/barra',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCamareroRoute = AuthenticatedCamareroRouteImport.update({
  id: '/camarero',
  path: '/camarero',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCocinaRoute = AuthenticatedCocinaRouteImport.update({
  id: '/cocina',
  path: '/cocina',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComandasRoute = AuthenticatedComandasRouteImport.update({
  id: '/comandas',
  path: '/comandas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDePieRoute = AuthenticatedDePieRouteImport.update({
  id: '/de-pie',
  path: '/de-pie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEsperaRoute = AuthenticatedEsperaRouteImport.update({
  id: '/espera',
  path: '/espera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExistenciasRoute =
  AuthenticatedExistenciasRouteImport.update({
    id: '/existencias',
    path: '/existencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFiadoRoute = AuthenticatedFiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MTokenRoute = MTokenRouteImport.update({
  id: '/m/$token',
  path: '/m/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAjustesRoute =
  AuthenticatedAdminAjustesRouteImport.update({
    id: '/admin/ajustes',
    path: '/admin/ajustes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminArticulosRoute =
  AuthenticatedAdminArticulosRouteImport.update({
    id: '/admin/articulos',
    path: '/admin/articulos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCartaImpresaRoute =
  AuthenticatedAdminCartaImpresaRouteImport.update({
    id: '/admin/carta-impresa',
    path: '/admin/carta-impresa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMesasRoute = AuthenticatedAdminMesasRouteImport.update({
  id: '/admin/mesas',
  path: '/admin/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPersonalRoute =
  AuthenticatedAdminPersonalRouteImport.update({
    id: '/admin/personal',
    path: '/admin/personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apuntarse': typeof ApuntarseRoute
  '/auth': typeof AuthRoute
  '/barra': typeof AuthenticatedBarraRoute
  '/camarero': typeof AuthenticatedCamareroRoute
  '/cocina': typeof AuthenticatedCocinaRoute
  '/comandas': typeof AuthenticatedComandasRoute
  '/de-pie': typeof AuthenticatedDePieRoute
  '/espera': typeof AuthenticatedEsperaRoute
  '/existencias': typeof AuthenticatedExistenciasRoute
  '/fiado': typeof AuthenticatedFiadoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/m/$token': typeof MTokenRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/articulos': typeof AuthenticatedAdminArticulosRoute
  '/admin/carta-impresa': typeof AuthenticatedAdminCartaImpresaRoute
  '/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/admin/personal': typeof AuthenticatedAdminPersonalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apuntarse': typeof ApuntarseRoute
  '/auth': typeof AuthRoute
  '/barra': typeof AuthenticatedBarraRoute
  '/camarero': typeof AuthenticatedCamareroRoute
  '/cocina': typeof AuthenticatedCocinaRoute
  '/comandas': typeof AuthenticatedComandasRoute
  '/de-pie': typeof AuthenticatedDePieRoute
  '/espera': typeof AuthenticatedEsperaRoute
  '/existencias': typeof AuthenticatedExistenciasRoute
  '/fiado': typeof AuthenticatedFiadoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/m/$token': typeof MTokenRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/articulos': typeof AuthenticatedAdminArticulosRoute
  '/admin/carta-impresa': typeof AuthenticatedAdminCartaImpresaRoute
  '/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/admin/personal': typeof AuthenticatedAdminPersonalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apuntarse': typeof ApuntarseRoute
  '/auth': typeof AuthRoute
  '/_authenticated/barra': typeof AuthenticatedBarraRoute
  '/_authenticated/camarero': typeof AuthenticatedCamareroRoute
  '/_authenticated/cocina': typeof AuthenticatedCocinaRoute
  '/_authenticated/comandas': typeof AuthenticatedComandasRoute
  '/_authenticated/de-pie': typeof AuthenticatedDePieRoute
  '/_authenticated/espera': typeof AuthenticatedEsperaRoute
  '/_authenticated/existencias': typeof AuthenticatedExistenciasRoute
  '/_authenticated/fiado': typeof AuthenticatedFiadoRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/m/$token': typeof MTokenRoute
  '/_authenticated/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/_authenticated/admin/articulos': typeof AuthenticatedAdminArticulosRoute
  '/_authenticated/admin/carta-impresa': typeof AuthenticatedAdminCartaImpresaRoute
  '/_authenticated/admin/mesas': typeof AuthenticatedAdminMesasRoute
  '/_authenticated/admin/personal': typeof AuthenticatedAdminPersonalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apuntarse'
    | '/auth'
    | '/barra'
    | '/camarero'
    | '/cocina'
    | '/comandas'
    | '/de-pie'
    | '/espera'
    | '/existencias'
    | '/fiado'
    | '/historial'
    | '/m/$token'
    | '/admin/ajustes'
    | '/admin/articulos'
    | '/admin/carta-impresa'
    | '/admin/mesas'
    | '/admin/personal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apuntarse'
    | '/auth'
    | '/barra'
    | '/camarero'
    | '/cocina'
    | '/comandas'
    | '/de-pie'
    | '/espera'
    | '/existencias'
    | '/fiado'
    | '/historial'
    | '/m/$token'
    | '/admin/ajustes'
    | '/admin/articulos'
    | '/admin/carta-impresa'
    | '/admin/mesas'
    | '/admin/personal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apuntarse'
    | '/auth'
    | '/_authenticated/barra'
    | '/_authenticated/camarero'
    | '/_authenticated/cocina'
    | '/_authenticated/comandas'
    | '/_authenticated/de-pie'
    | '/_authenticated/espera'
    | '/_authenticated/existencias'
    | '/_authenticated/fiado'
    | '/_authenticated/historial'
    | '/m/$token'
    | '/_authenticated/admin/ajustes'
    | '/_authenticated/admin/articulos'
    | '/_authenticated/admin/carta-impresa'
    | '/_authenticated/admin/mesas'
    | '/_authenticated/admin/personal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApuntarseRoute: typeof ApuntarseRoute
  AuthRoute: typeof AuthRoute
  MTokenRoute: typeof MTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apuntarse': {
      id: '/apuntarse'
      path: '/apuntarse'
      fullPath: '/apuntarse'
      preLoaderRoute: typeof ApuntarseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/barra': {
      id: '/_authenticated/barra'
      path: '/barra'
      fullPath: '/barra'
      preLoaderRoute: typeof AuthenticatedBarraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camarero': {
      id: '/_authenticated/camarero'
      path: '/camarero'
      fullPath: '/camarero'
      preLoaderRoute: typeof AuthenticatedCamareroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cocina': {
      id: '/_authenticated/cocina'
      path: '/cocina'
      fullPath: '/cocina'
      preLoaderRoute: typeof AuthenticatedCocinaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comandas': {
      id: '/_authenticated/comandas'
      path: '/comandas'
      fullPath: '/comandas'
      preLoaderRoute: typeof AuthenticatedComandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/de-pie': {
      id: '/_authenticated/de-pie'
      path: '/de-pie'
      fullPath: '/de-pie'
      preLoaderRoute: typeof AuthenticatedDePieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espera': {
      id: '/_authenticated/espera'
      path: '/espera'
      fullPath: '/espera'
      preLoaderRoute: typeof AuthenticatedEsperaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/existencias': {
      id: '/_authenticated/existencias'
      path: '/existencias'
      fullPath: '/existencias'
      preLoaderRoute: typeof AuthenticatedExistenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiado': {
      id: '/_authenticated/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof AuthenticatedFiadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/m/$token': {
      id: '/m/$token'
      path: '/m/$token'
      fullPath: '/m/$token'
      preLoaderRoute: typeof MTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/ajustes': {
      id: '/_authenticated/admin/ajustes'
      path: '/admin/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AuthenticatedAdminAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/articulos': {
      id: '/_authenticated/admin/articulos'
      path: '/admin/articulos'
      fullPath: '/admin/articulos'
      preLoaderRoute: typeof AuthenticatedAdminArticulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/carta-impresa': {
      id: '/_authenticated/admin/carta-impresa'
      path: '/admin/carta-impresa'
      fullPath: '/admin/carta-impresa'
      preLoaderRoute: typeof AuthenticatedAdminCartaImpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mesas': {
      id: '/_authenticated/admin/mesas'
      path: '/admin/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AuthenticatedAdminMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/personal': {
      id: '/_authenticated/admin/personal'
      path: '/admin/personal'
      fullPath: '/admin/personal'
      preLoaderRoute: typeof AuthenticatedAdminPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBarraRoute: typeof AuthenticatedBarraRoute
  AuthenticatedCamareroRoute: typeof AuthenticatedCamareroRoute
  AuthenticatedCocinaRoute: typeof AuthenticatedCocinaRoute
  AuthenticatedComandasRoute: typeof AuthenticatedComandasRoute
  AuthenticatedDePieRoute: typeof AuthenticatedDePieRoute
  AuthenticatedEsperaRoute: typeof AuthenticatedEsperaRoute
  AuthenticatedExistenciasRoute: typeof AuthenticatedExistenciasRoute
  AuthenticatedFiadoRoute: typeof AuthenticatedFiadoRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedAdminAjustesRoute: typeof AuthenticatedAdminAjustesRoute
  AuthenticatedAdminArticulosRoute: typeof AuthenticatedAdminArticulosRoute
  AuthenticatedAdminCartaImpresaRoute: typeof AuthenticatedAdminCartaImpresaRoute
  AuthenticatedAdminMesasRoute: typeof AuthenticatedAdminMesasRoute
  AuthenticatedAdminPersonalRoute: typeof AuthenticatedAdminPersonalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBarraRoute: AuthenticatedBarraRoute,
  AuthenticatedCamareroRoute: AuthenticatedCamareroRoute,
  AuthenticatedCocinaRoute: AuthenticatedCocinaRoute,
  AuthenticatedComandasRoute: AuthenticatedComandasRoute,
  AuthenticatedDePieRoute: AuthenticatedDePieRoute,
  AuthenticatedEsperaRoute: AuthenticatedEsperaRoute,
  AuthenticatedExistenciasRoute: AuthenticatedExistenciasRoute,
  AuthenticatedFiadoRoute: AuthenticatedFiadoRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedAdminAjustesRoute: AuthenticatedAdminAjustesRoute,
  AuthenticatedAdminArticulosRoute: AuthenticatedAdminArticulosRoute,
  AuthenticatedAdminCartaImpresaRoute: AuthenticatedAdminCartaImpresaRoute,
  AuthenticatedAdminMesasRoute: AuthenticatedAdminMesasRoute,
  AuthenticatedAdminPersonalRoute: AuthenticatedAdminPersonalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApuntarseRoute: ApuntarseRoute,
  AuthRoute: AuthRoute,
  MTokenRoute: MTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
